### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "hashing@gmail.com",
    "password": "abcdefgh"
}

### Signin User

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "hashing@gmail.com",
    "password": "abcdefgh"
}

### Find a particular user with the given ID

GET http://localhost:3000/auth/3

### Find all users with a given email

GET http://localhost:3000/auth?email=hashing@gmail.com

### Delete a user with the given id

DELETE http://localhost:3000/auth/8

### Update a user

PATCH http://localhost:3000/auth/333
Content-Type: application/json

{
    "email": "new23@gmail.com",
    "password": "newPassword"
}

### Set color in cookie

Get http://localhost:3000/auth/colors/red

### Get color stored in cookie

Get http://localhost:3000/auth/colors